### ISSUE TITLE
Support for Identity Broker

### ISSUE THREAD

**Issue by SofianeB** [indigo-dc/oidcc#200]
Hi, 

I am trying to connect our jupyterhub instance via keycloak to INDIGO IAM (https://iam-test.indigo-datacloud.eu/.well-known/openid-configuration). The redirection to the login/confirmation page works perfectly. 
Unfortunately, I am getting cannot get access_token from server. 

Did I miss something during configuration?

I created an account and then a client, exported the JSON file and upload it to keycloak. 

Thank you. 

Best, 

Sofiane.

**Comment by bwegh** [comment]
unreleated to oidcc as seen in linked issue
